### ISSUE TITLE
context.getRemainingTime

### ISSUE THREAD

**Issue by mattmeye** [SamVerschueren/aws-lambda-mock-context#10]
Hey,

can you implement the context.getRemainingTime-Function correctly, by using an timeout constant in options?

**Comment by SamVerschueren** [comment]
Hi @mattmeye, can you elaborate? Do you want to provide the value that should be returned by the `getRemainingTimeInMillis` function? Or do you want to provide the `timeout` of the Lambda function as an option and really track how long it takes to run the function that gets executed?

**Comment by mattmeye** [comment]
Many Thanks. That's what I wanted.

**Comment by SamVerschueren** [comment]
Alright. I want to implement #11 as well first and then I will do a new release. Probably later today.

**Comment by SamVerschueren** [comment]
Released in `3.1.0` :tada:
