### ISSUE TITLE
Accounting for different invocation types

### ISSUE THREAD

**Issue by nikhilaravi** [SamVerschueren/aws-lambda-mock-context#7]
Hi! Thanks for creating this module. Just wondering if you are planning to extend it to account for different invocation types i.e. Event or Request/Response. From the AWS docs about the context.success function:

> If the Lambda function is invoked using the Event invocation type (asynchronous invocation), the method will return "HTTP status 202, request accepted" response.
> If the Lambda function is invoked using the RequestResponse invocation type (synchronous invocation), the method will return HTTP status 200 (OK) and set the response  body to the string representation of the result.

**Comment by SamVerschueren** [comment]
@nikhilaravi can you elaborate a little bit more? I think I don't follow you entirely.

`aws-lambda-mock-context` was created for easier testing of your lambda function. Together with [aws-lambda-pify](https://github.com/samverschueren/aws-lambda-pify) which uses this mock context.

The mock context does not have anything to do with calling another lambda function sync (e.g. RequestResponse) or async (e.g. Event). So feel free to give an example with a use case and how you want to lib to behave.

**Comment by nikhilaravi** [comment]
@SamVerschueren thanks for your reply. How do you go about testing different invocation types for the same lambda function? Or is it not necessary to do this?

**Comment by SamVerschueren** [comment]
No need to test that. They are both handled the same way, it's just the caller that isn't waiting for a response.

**Comment by nikhilaravi** [comment]
@SamVerschueren okay great thanks!

**Comment by SamVerschueren** [comment]
No problem :)
