### ISSUE TITLE
Times out when using states (Alexa.CreateStateHandler)

### ISSUE THREAD

**Issue by ellier** [SamVerschueren/aws-lambda-mock-context#9]
I'm using states in my handlers. In my event for the test, I add STATE: '_READY' to attributes. As soon as I do this, the test throws a timeout error.

**Comment by ellier** [comment]
Never mind. I needed to change "new": true to "new": false in session.

One thing that doesn't seem to work is when you do this.emit('SomeIntent'). In that case you get a timeout. I don't know if this is a bug or intended.

**Comment by SamVerschueren** [comment]
I never used Alexa and or Lambda to create an Alexa Skill (is this what it is called?).So it might be that the mock context doesn't support some things. If you could show me the docs and also a little example of what you are doing, I might be able to see what's going wrong.

**Comment by ellier** [comment]
[https://paste.laravel.io/KLn6o](url)

This test passes as we're calling the SayHello intent directly. On the other hand, If you go to line 88 and change the intent name to NewSession, the test will fail as SayHello is never called. In an Alexa skill, this.emit('SayHello') would call SayHello. That doesn't happen in the test and I get the timeout error below:

    Testing Hello
    1) "before all" hook

    0 passing (2s)
    1 failing

    1) Testing Hello "before all" hook:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
